config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'categories#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users do
    resources :categories do
      resources :expenses
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, :email, presence: true, length: { maximum: 50 }
  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_category

  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.where(user_id: current_user.id).order('created_at DESC')
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @categories = current_user.categories
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = @category.expenses.new(expense_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to user_category_expenses_path(params[:category_id]), notice: 'Expense was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: user_category_expenses_path(current_user, @category)) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div class="form-group custom-dropdown">
  <label for="category-select" class="control-label">Select Category</label>
  <div class="options">
<%= form.collection_select :category_ids, current_user.categories, :id, :name, {}, { multiple: true, class: 'form-select', required: true, aria_label: "Disabled select example" } %>
  </div>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<h2 class="transaction-heading">TRANSACTIONS</h2>
<div class="page-header">
  <h2 class="categories-heading">Expenses of <b class="cat-name"><%=@category.name%></b></h2>
</div>

<h3>
  Total expenses: <%= @category.total_expenses(current_user).round(2) %>
</h3>

<div id="expenses" class="expenses">
  <% @expenses.each do |expense| %>
    <ul class="explist">
      <li> <%= expense.name %> </li>
      <li> <%= expense.amount %> </li>
    </ul>
  <% end %>
</div>

<div class="links-cat">
  <%= link_to "Back to Category", user_categories_path(current_user), class: 'back-to-category' %>
</div>

<div class="bottom-div">
<%= link_to "NEW EXPENSE", new_user_category_expense_path(current_user, @category), class: 'bottom-button' %>
</div>

app/views/expenses/new.html.erb
<h2 class="transaction-heading">TRANSACTIONS</h2>
<div class="page-header">
  <h2 class="categories-heading">New expense</h2>
</div>

<%= render "form", expense: @expense %>

<br>

<div>
    <%= link_to "Back to expenses", user_category_expenses_path(current_user, @category), class: 'back-to-category' %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>